version = 3.9.8
runner.dialect = scala3
maxColumn: 120

rewrite.rules: [
  Imports
  RedundantBraces
  RedundantParens
  PreferCurlyFors
]

align.openParenCallSite: false
align.openParenDefnSite: false
danglingParentheses.callSite: false
danglingParentheses.defnSite: false

// don't align arrows in match statements
align.preset: none

rewrite {
  imports.sort: scalastyle

  redundantBraces {
    generalExpressions: false
    defnBodies: none
    stringInterpolation: true
  }
}

docstrings {
  style: Asterisk
  blankFirstLine: true
  removeEmpty: true
  wrap: fold
}

newlines.topLevelStatementBlankLines: [
  {
    regex: "Import"
    blanks: 1
  }
]

project.excludeFilters: [ "metals.sbt" ]

fileOverride {
  // sbt related files - *.sbt & project/*.scala
  "glob:**/*.sbt" {
    runner.dialect: sbt1
    // align libraryDependencies
    align.preset: most
  }
  "glob:**/project/*.scala" {
    runner.dialect: sbt1
    // align libraryDependencies
    align.preset: more
  }
}
