version = 3.9.8
maxColumn = 120
runner.dialect = scala3
align.preset = none
newlines.topLevelStatements = [before]
rewrite.rules = [SortImports]

docstrings {
  style: Asterisk
  blankFirstLine: true
  removeEmpty: true
  wrap: fold
}